# -*- coding: utf-8 -*-
"""Légumes et fruits."""
from common import vegan

VEGETABLES = [
    ("chou-bruxelles", "Choux de Bruxelles", "Brussels sprouts", "Coles de Bruselas",
     "vegetable", "base", 43, 3.4, 9.0, 0.3, 3.8, 0, 150, vegan(),
     "Parmi les légumes les plus denses en vitamine K et en fibres — rôtis au four, ils ne ressemblent plus du tout à leur réputation.",
     "Among the densest vegetables in vitamin K and fibre — roasted, they taste nothing like their reputation.",
     "De las verduras más densas en vitamina K y fibra; asadas no se parecen en nada a su fama."),
    ("chou-rouge", "Chou rouge", "Red cabbage", "Lombarda",
     "vegetable", "base", 31, 1.4, 7.4, 0.2, 2.1, 0, 100, vegan(),
     "Les anthocyanes de la myrtille au prix du chou, et cru il croque des semaines au réfrigérateur.",
     "Blueberry's anthocyanins at cabbage price, and raw it stays crisp for weeks in the fridge.",
     "Los antocianos del arándano a precio de col, y cruda aguanta crujiente semanas en la nevera."),
    ("chou-kale", "Chou kale", "Kale", "Kale",
     "vegetable", "base", 49, 4.3, 9.0, 0.9, 3.6, 0, 100, vegan(),
     "Plus de protéines et de calcium que n'importe quelle salade — massé à l'huile, il cesse d'être une punition.",
     "More protein and calcium than any lettuce — massaged with oil, it stops being a punishment.",
     "Más proteína y calcio que cualquier lechuga; masajeado con aceite deja de ser un castigo."),
    ("blettes", "Blettes", "Swiss chard", "Acelgas",
     "vegetable", "base", 19, 1.8, 3.7, 0.2, 1.6, 0, 150, vegan(),
     "Le magnésium des épinards, la mâche en plus — les côtes et les feuilles font deux légumes en un.",
     "Spinach's magnesium with more bite — stalks and leaves make two vegetables in one.",
     "El magnesio de las espinacas con más textura: pencas y hojas son dos verduras en una."),
    ("celeri-branche", "Céleri branche", "Celery", "Apio",
     "vegetable", "base", 16, 0.7, 3.0, 0.2, 1.6, 0, 100, vegan(),
     "Presque zéro calorie et un croquant qui occupe : le légume des faims de dix-sept heures.",
     "Nearly zero calories and a crunch that keeps you busy: the vegetable for five-o'clock hunger.",
     "Casi cero calorías y un crujido que entretiene: la verdura del hambre de las cinco."),
    ("celeri-rave", "Céleri-rave", "Celeriac", "Apionabo",
     "vegetable", "base", 42, 1.5, 9.0, 0.3, 1.8, 0, 150, vegan(),
     "En purée, il imite la pomme de terre pour moitié moins de calories.",
     "Mashed, it impersonates potato at half the calories.",
     "En puré imita a la patata con la mitad de calorías."),
    ("fenouil", "Fenouil", "Fennel", "Hinojo",
     "vegetable", "base", 31, 1.2, 7.3, 0.2, 3.1, 0, 150, vegan(),
     "Cru il croque comme le céleri, cuit il fond comme l'oignon — deux légumes pour le prix d'un.",
     "Raw it crunches like celery, cooked it melts like onion — two vegetables for the price of one.",
     "Crudo cruje como el apio, cocido se funde como la cebolla: dos verduras por el precio de una."),
    ("poireau", "Poireau", "Leek", "Puerro",
     "vegetable", "base", 61, 1.5, 14.0, 0.3, 1.8, 0, 150, vegan(),
     "L'oignon doux des plats mijotés, et ses fibres nourrissent le microbiote plus que la plupart des légumes.",
     "The mild onion of slow dishes, and its fibres feed the microbiome more than most vegetables do.",
     "La cebolla suave de los guisos, y su fibra alimenta el microbioma más que la mayoría de verduras."),
    ("aubergine", "Aubergine", "Aubergine", "Berenjena",
     "vegetable", "base", 25, 1.0, 6.0, 0.2, 3.0, 0, 150, vegan(),
     "Une éponge à huile au four ou à la poêle — rôtie entière, elle garde sa légèreté et son fondant.",
     "An oil sponge in the pan — roasted whole, it keeps both its lightness and its melt.",
     "Una esponja de aceite en la sartén; asada entera conserva su ligereza y su cremosidad."),
    ("concombre", "Concombre", "Cucumber", "Pepino",
     "vegetable", "base", 15, 0.7, 3.6, 0.1, 0.5, 0, 150, vegan(),
     "De l'eau qui croque : le volume dans l'assiette qui ne coûte rien au total.",
     "Crunchy water: plate volume that costs the total nothing.",
     "Agua que cruje: volumen en el plato que no cuesta nada al total."),
    ("butternut", "Courge butternut", "Butternut squash", "Calabaza butternut",
     "vegetable", "base", 45, 1.0, 11.5, 0.1, 2.0, 0, 200, vegan(),
     "La douceur d'une purée de patate douce pour moitié moins de calories, et un stock d'hiver qui ne périme pas.",
     "Sweet-potato-mash sweetness at half the calories, and a winter stock that never spoils.",
     "El dulzor de un puré de boniato con la mitad de calorías, y una despensa de invierno que no caduca."),
    ("potiron", "Potiron", "Pumpkin", "Calabaza",
     "vegetable", "base", 26, 1.0, 6.5, 0.1, 0.5, 0, 200, vegan(),
     "Le légume-soupe de l'hiver : du bêta-carotène en quantité pour presque rien en calories.",
     "The winter soup vegetable: plenty of beta-carotene for nearly nothing in calories.",
     "La verdura-sopa del invierno: betacaroteno en cantidad por casi nada en calorías."),
    ("navet", "Navet", "Turnip", "Nabo",
     "vegetable", "base", 28, 0.9, 6.4, 0.1, 1.8, 0, 150, vegan(),
     "Le discret des pot-au-feu : de la famille du brocoli, avec les mêmes composés soufrés protecteurs.",
     "The quiet one in the stew: from broccoli's family, with the same protective sulfur compounds.",
     "El discreto del cocido: de la familia del brócoli, con los mismos compuestos azufrados protectores."),
    ("radis", "Radis", "Radishes", "Rábanos",
     "vegetable", "base", 16, 0.7, 3.4, 0.1, 1.6, 0, 100, vegan(),
     "Le croquant poivré de l'apéritif qui ne doit rien au paquet de chips.",
     "The peppery crunch of apéritif hour that owes nothing to the crisps bag.",
     "El crujiente picante del aperitivo que no le debe nada a la bolsa de patatas."),
    ("endive", "Endive", "Endive", "Endibia",
     "vegetable", "base", 17, 0.9, 4.0, 0.1, 3.1, 0, 150, vegan(),
     "L'amertume qui ouvre l'appétit et des fibres inuline qui nourrissent le microbiote.",
     "The bitterness that opens the appetite, and inulin fibres that feed the microbiome.",
     "El amargor que abre el apetito y fibras de inulina que alimentan el microbioma."),
    ("mache", "Mâche", "Lamb's lettuce", "Canónigos",
     "vegetable", "base", 21, 2.0, 3.6, 0.4, 1.5, 0, 80, vegan(),
     "La salade qui contient de vrais oméga-3 végétaux — rare dans un rayon où la laitue n'apporte que du croquant.",
     "The salad leaf with real plant omega-3s — rare on a shelf where lettuce brings only crunch.",
     "La ensalada con auténticos omega-3 vegetales: rara en un estante donde la lechuga solo aporta crujido."),
    ("roquette", "Roquette", "Rocket", "Rúcula",
     "vegetable", "base", 25, 2.6, 3.7, 0.7, 1.6, 0, 80, vegan(),
     "Les nitrates qui dilatent les vaisseaux — la même famille de composés que la betterave des coureurs.",
     "The vessel-dilating nitrates — the same compound family as the runner's beetroot.",
     "Los nitratos que dilatan los vasos: la misma familia de compuestos que la remolacha de los corredores."),
    ("cresson", "Cresson", "Watercress", "Berros",
     "vegetable", "base", 21, 2.3, 2.7, 0.3, 1.1, 0, 80, vegan(),
     "Le légume le mieux classé en nutriments par calorie des tables de référence — littéralement imbattable.",
     "The top-ranked vegetable for nutrients per calorie in the reference tables — literally unbeatable.",
     "La verdura mejor clasificada en nutrientes por caloría de las tablas de referencia: literalmente imbatible."),
    ("artichaut", "Artichaut", "Artichoke", "Alcachofa",
     "vegetable", "base", 47, 3.3, 10.5, 0.2, 5.4, 0, 150, vegan(),
     "Un des champions des fibres — et l'inuline qu'il contient est celle que le microbiote préfère.",
     "One of the fibre champions — and its inulin is the kind the microbiome likes best.",
     "Uno de los campeones de la fibra, y su inulina es la que más le gusta al microbioma."),
    ("germes-soja", "Germes de soja", "Bean sprouts", "Brotes de soja",
     "vegetable", "base", 30, 3.0, 4.5, 0.2, 1.8, 0, 100, vegan(),
     "Le croquant des plats sautés, avec un peu de protéines là où la plupart des légumes n'en ont pas.",
     "The stir-fry crunch, with a little protein where most vegetables have none.",
     "El crujiente del salteado, con algo de proteína donde la mayoría de verduras no tienen."),
]

FRUITS = [
    ("poire", "Poire", "Pear", "Pera",
     "fruit", "base", 57, 0.4, 15.0, 0.1, 3.1, 0, 150, vegan(),
     "Plus de fibres que la pomme, dont l'essentiel dans la peau : elle se mange en entier.",
     "More fibre than an apple, most of it in the skin: eat it whole.",
     "Más fibra que la manzana, y casi toda en la piel: se come entera."),
    ("peche", "Pêche", "Peach", "Melocotón",
     "fruit", "base", 39, 0.9, 9.5, 0.3, 1.5, 0, 150, vegan(),
     "Le fruit d'été le plus léger après la pastèque — deux pêches valent une banane.",
     "The lightest summer fruit after watermelon — two peaches equal one banana.",
     "La fruta de verano más ligera tras la sandía: dos melocotones valen un plátano."),
    ("abricot", "Abricots", "Apricots", "Albaricoques",
     "fruit", "base", 48, 1.4, 11.0, 0.4, 2.0, 0, 120, vegan(),
     "Trois abricots, une dose de bêta-carotène, cinquante kilocalories : l'en-cas d'été réglé.",
     "Three apricots, a dose of beta-carotene, fifty kilocalories: the summer snack, solved.",
     "Tres albaricoques, una dosis de betacaroteno, cincuenta kilocalorías: la merienda de verano resuelta."),
    ("prune", "Prunes", "Plums", "Ciruelas",
     "fruit", "base", 46, 0.7, 11.4, 0.3, 1.4, 0, 120, vegan(),
     "Les polyphénols sombres de la peau, et un transit que les pruneaux n'ont pas attendu pour aider.",
     "The dark polyphenols of the skin, and a transit the dried version never had a monopoly on helping.",
     "Los polifenoles oscuros de la piel, y un tránsito al que ya ayudan sin esperar a ser pasas."),
    ("cerises", "Cerises", "Cherries", "Cerezas",
     "fruit", "base", 63, 1.1, 16.0, 0.2, 2.1, 0, 125, vegan(),
     "Les anthocyanes qui apaisent l'inflammation post-séance — le jus de cerise acide est un classique de la récupération.",
     "The anthocyanins that calm post-session inflammation — tart cherry juice is a recovery classic.",
     "Los antocianos que calman la inflamación tras la sesión: el zumo de cereza ácida es un clásico de la recuperación."),
    ("framboises", "Framboises", "Raspberries", "Frambuesas",
     "fruit", "base", 52, 1.2, 12.0, 0.7, 6.5, 0, 125, vegan(),
     "6,5 g de fibres aux 100 g : le record du rayon fruits, à égalité avec bien des légumes secs.",
     "6.5 g of fibre per 100 g: the fruit-shelf record, level with many a dried legume.",
     "6,5 g de fibra por 100 g: el récord de la frutería, a la altura de muchas legumbres."),
    ("mures", "Mûres", "Blackberries", "Moras",
     "fruit", "base", 43, 1.4, 10.0, 0.5, 5.3, 0, 125, vegan(),
     "Presque autant de fibres que la framboise, et gratuites au bord des chemins d'août.",
     "Nearly raspberry-level fibre, and free along the paths of August.",
     "Casi tanta fibra como la frambuesa, y gratis en los caminos de agosto."),
    ("cassis", "Cassis", "Blackcurrants", "Grosellas negras",
     "fruit", "base", 63, 1.4, 15.0, 0.4, 4.3, 0, 100, vegan(),
     "Quatre fois la vitamine C de l'orange, dans une baie que personne ne pense à compter.",
     "Four times the vitamin C of an orange, in a berry nobody thinks to count.",
     "Cuatro veces la vitamina C de la naranja, en una baya que nadie piensa en contar."),
    ("mangue", "Mangue", "Mango", "Mango",
     "fruit", "base", 60, 0.8, 15.0, 0.4, 1.6, 0, 150, vegan(),
     "Plus sucrée que la pomme mais pleine de bêta-carotène — un dessert qui se suffit.",
     "Sweeter than an apple but full of beta-carotene — a dessert that needs nothing else.",
     "Más dulce que la manzana pero llena de betacaroteno: un postre que se basta solo."),
    ("ananas", "Ananas", "Pineapple", "Piña",
     "fruit", "base", 50, 0.5, 13.0, 0.1, 1.4, 0, 150, vegan(),
     "L'acidité qui réveille un fromage blanc — et sa broméline attendrit même la viande.",
     "The sharpness that wakes up fromage blanc — and its bromelain even tenderises meat.",
     "La acidez que despierta un queso fresco, y su bromelina hasta ablanda la carne."),
    ("pasteque", "Pastèque", "Watermelon", "Sandía",
     "fruit", "base", 30, 0.6, 7.5, 0.2, 0.4, 0, 250, vegan(),
     "Le fruit le plus léger du rayon : une part généreuse coûte moins qu'un biscuit.",
     "The lightest fruit on the shelf: a generous slice costs less than one biscuit.",
     "La fruta más ligera del estante: una tajada generosa cuesta menos que una galleta."),
    ("melon", "Melon", "Cantaloupe melon", "Melón cantalupo",
     "fruit", "base", 34, 0.8, 8.0, 0.2, 0.9, 0, 200, vegan(),
     "L'entrée d'été qui hydrate autant qu'elle nourrit — et du potassium pour les jours de forte chaleur.",
     "The summer starter that hydrates as much as it feeds — with potassium for the hottest days.",
     "La entrada de verano que hidrata tanto como alimenta, con potasio para los días de más calor."),
    ("clementine", "Clémentines", "Clementines", "Clementinas",
     "fruit", "base", 47, 0.9, 12.0, 0.2, 1.7, 0, 120, vegan(),
     "Le fruit d'hiver qui se transporte, s'épluche en dix secondes et se mange sans y penser.",
     "The winter fruit that travels, peels in ten seconds and gets eaten without thinking.",
     "La fruta de invierno que viaja, se pela en diez segundos y se come sin pensar."),
    ("pamplemousse", "Pamplemousse", "Grapefruit", "Pomelo",
     "fruit", "base", 42, 0.8, 10.5, 0.1, 1.6, 0, 150, vegan(),
     "L'amertume qui cale mieux que le sucré — attention seulement à certains médicaments, l'interaction est réelle.",
     "The bitterness that satisfies better than sweetness — just mind some medications, the interaction is real.",
     "El amargor que sacia mejor que el dulzor; ojo solo con algunos medicamentos, la interacción es real."),
    ("grenade", "Grenade", "Pomegranate", "Granada",
     "fruit", "base", 83, 1.7, 19.0, 1.2, 4.0, 0, 100, vegan(),
     "Des polyphénols parmi les plus étudiés du rayon, et des graines qui croquent comme rien d'autre.",
     "Polyphenols among the most studied on the shelf, and seeds that crunch like nothing else.",
     "Polifenoles de los más estudiados del estante, y granos que crujen como ninguna otra cosa."),
    ("figue", "Figues fraîches", "Fresh figs", "Higos frescos",
     "fruit", "base", 74, 0.8, 19.0, 0.3, 2.9, 0, 100, vegan(),
     "Le fruit du calcium — rare chez les fruits — et une douceur qui remplace un dessert.",
     "The calcium fruit — rare among fruit — with a sweetness that stands in for dessert.",
     "La fruta del calcio, raro entre las frutas, con un dulzor que sustituye a un postre."),
    ("citron", "Citron", "Lemon", "Limón",
     "fruit", "base", 29, 1.1, 6.0, 0.3, 2.8, 0, 60, vegan(),
     "L'assaisonnement zéro calorie : il remplace la moitié du sel et la moitié des sauces.",
     "The zero-calorie seasoning: it replaces half the salt and half the sauces.",
     "El aliño de cero calorías: sustituye a la mitad de la sal y a la mitad de las salsas."),
    ("kaki", "Kaki", "Persimmon", "Caqui",
     "fruit", "base", 70, 0.6, 18.0, 0.2, 3.6, 0, 150, vegan(),
     "Le fruit d'automne oublié : plus de fibres que la pomme, et une chair qui se mange à la cuillère.",
     "The forgotten autumn fruit: more fibre than an apple, and a flesh you eat with a spoon.",
     "La fruta de otoño olvidada: más fibra que la manzana y una carne que se come a cucharadas."),
    ("abricots-secs", "Abricots secs", "Dried apricots", "Orejones",
     "fruit", "moderate", 241, 3.4, 53.0, 0.5, 7.3, 0, 40, vegan(),
     "Le fruit moins l'eau : les fibres et le potassium concentrés, mais le sucre aussi — quatre abricots secs valent le fruit frais entier.",
     "The fruit minus the water: fibre and potassium concentrated, but so is the sugar — four dried apricots equal the whole fresh fruit.",
     "La fruta sin el agua: fibra y potasio concentrados, pero el azúcar también; cuatro orejones valen la fruta fresca entera."),
    ("pruneaux", "Pruneaux", "Prunes", "Ciruelas pasas",
     "fruit", "moderate", 240, 2.2, 57.0, 0.4, 7.1, 0, 40, vegan(),
     "Le remède au transit le mieux documenté du rayon — en comptant ses 240 kcal aux 100 g.",
     "The best-documented transit remedy on the shelf — counting its 240 kcal per 100 g.",
     "El remedio para el tránsito mejor documentado del estante, contando sus 240 kcal por 100 g."),
    ("raisins-secs", "Raisins secs", "Raisins", "Pasas",
     "fruit", "moderate", 300, 3.1, 72.0, 0.5, 4.0, 0, 30, vegan(),
     "Le sucre du raisin sans son eau : une poignée en randonnée oui, le paquet devant l'écran non.",
     "Grape sugar without the water: a handful on a hike yes, the bag in front of a screen no.",
     "El azúcar de la uva sin su agua: un puñado en la ruta sí, la bolsa frente a la pantalla no."),
    ("compote-ssa", "Compote sans sucre ajouté", "No-added-sugar apple purée", "Compota sin azúcar añadido",
     "fruit", "base", 45, 0.3, 11.0, 0.2, 1.7, 0, 100, vegan(),
     "La pomme, moins la mâche : honnête au goûter, mais le fruit entier rassasie davantage.",
     "Apple minus the chewing: honest as a snack, but the whole fruit fills you more.",
     "La manzana sin la masticación: honesta para merendar, pero la fruta entera sacia más."),
]
