# -*- coding: utf-8 -*-
"""Protéines végétales et féculents. Féculents pesés cuits, comme le rayon."""
from common import vegan

PLANT_PROTEINS = [
    ("haricots-rouges", "Haricots rouges", "Kidney beans", "Alubias rojas",
     "protein", "base", 127, 8.7, 16.0, 0.5, 6.4, 0, 200, vegan(),
     "Le trio protéines-fibres-fer des légumineuses, dans la variété qui tient le mieux le chili.",
     "The legume protein-fibre-iron trio, in the variety that holds a chili best.",
     "El trío proteína-fibra-hierro de las legumbres, en la variedad que mejor aguanta un chili."),
    ("haricots-blancs", "Haricots blancs", "White beans", "Alubias blancas",
     "protein", "base", 115, 8.0, 15.0, 0.6, 6.3, 0, 200, vegan(),
     "Les mêmes armes que les rouges, la peau plus fine : ceux par lesquels commencer si les légumineuses te pèsent.",
     "The same weapons as red beans with a thinner skin: the ones to start with if legumes sit heavy.",
     "Las mismas armas que las rojas con la piel más fina: por las que empezar si las legumbres te pesan."),
    ("pois-casses", "Pois cassés", "Split peas", "Guisantes partidos",
     "protein", "base", 116, 8.3, 15.5, 0.4, 8.3, 0, 200, vegan(),
     "Plus de fibres que n'importe quel autre plat de ce rayon, et pas de trempage : la légumineuse des soirs pressés.",
     "More fibre than anything else on this shelf, and no soaking: the weeknight legume.",
     "Más fibra que nada en este estante y sin remojo: la legumbre de las noches con prisa."),
    ("feves", "Fèves", "Broad beans", "Habas",
     "protein", "base", 88, 7.6, 10.0, 0.4, 5.4, 0, 200, vegan(),
     "La légumineuse la plus légère du rayon : des protéines et des fibres pour le prix calorique d'un légume.",
     "The lightest legume on the shelf: protein and fibre at a vegetable's caloric price.",
     "La legumbre más ligera del estante: proteína y fibra al precio calórico de una verdura."),
    ("tofu-fume", "Tofu fumé", "Smoked tofu", "Tofu ahumado",
     "protein", "base", 150, 16.0, 1.5, 9.0, 1.5, 0, 125, vegan(),
     "Le tofu qui a déjà du goût en sortant du paquet — la porte d'entrée honnête vers le nature.",
     "The tofu that tastes of something straight from the pack — the honest gateway to plain.",
     "El tofu que ya sabe a algo al salir del paquete: la puerta de entrada honesta al natural."),
    ("houmous", "Houmous", "Hummus", "Hummus",
     "fat", "moderate", 250, 7.0, 12.0, 18.0, 5.0, 0, 50, vegan(),
     "Des pois chiches, oui — noyés dans le tahini et l'huile : c'est une matière grasse qui a bonne réputation.",
     "Chickpeas, yes — drowned in tahini and oil: it is a fat with a good reputation.",
     "Garbanzos, sí, ahogados en tahini y aceite: es una grasa con buena reputación."),
    ("falafel", "Falafels", "Falafel", "Faláfel",
     "protein", "moderate", 330, 13.0, 30.0, 17.0, 5.0, 0, 100, vegan(),
     "Des pois chiches passés par la friture : la moitié des calories vient de l'huile du bain.",
     "Chickpeas that went through the fryer: half the calories come from the oil bath.",
     "Garbanzos pasados por la freidora: la mitad de las calorías viene del baño de aceite."),
]

GRAINS = [
    ("boulgour", "Boulgour", "Bulgur", "Bulgur",
     "carb", "base", 118, 4.3, 22.0, 0.4, 3.5, 0, 180, vegan(gluten=True),
     "Du blé précuit qui garde plus de fibres que la semoule — prêt en dix minutes, rassasiant plus longtemps.",
     "Pre-cooked wheat that keeps more fibre than couscous — ready in ten minutes, filling for longer.",
     "Trigo precocido que conserva más fibra que el cuscús: listo en diez minutos, sacia más tiempo."),
    ("semoule", "Semoule / couscous", "Couscous", "Cuscús",
     "carb", "base", 125, 4.0, 24.0, 0.3, 2.2, 0, 180, vegan(gluten=True),
     "Le féculent le plus rapide de la cuisine : cinq minutes, zéro surveillance, et la graine porte les épices.",
     "The fastest starch in the kitchen: five minutes, zero watching, and the grain carries the spices.",
     "El farináceo más rápido de la cocina: cinco minutos, cero vigilancia, y el grano lleva las especias."),
    ("orge-perle", "Orge perlé", "Pearl barley", "Cebada perlada",
     "carb", "base", 123, 2.3, 26.0, 0.4, 3.8, 0, 180, vegan(gluten=True),
     "Les bêta-glucanes de l'avoine dans un grain qui se cuisine comme un risotto.",
     "Oat's beta-glucans in a grain that cooks like a risotto.",
     "Los betaglucanos de la avena en un grano que se cocina como un risotto."),
    ("epeautre", "Épeautre", "Spelt", "Espelta",
     "carb", "base", 127, 5.5, 24.0, 0.8, 3.9, 0, 180, vegan(gluten=True),
     "Le blé ancien : un peu plus de protéines que le riz complet, une mâche qui tient le couteau.",
     "The ancient wheat: a little more protein than brown rice, a chew that stands its ground.",
     "El trigo antiguo: algo más de proteína que el arroz integral y una textura con carácter."),
    ("millet", "Millet", "Millet", "Mijo",
     "carb", "base", 119, 3.5, 23.0, 1.0, 1.3, 0, 180, vegan(),
     "Sans gluten et doux au goût : le remplaçant du couscous quand le blé est exclu.",
     "Gluten-free and mild: the couscous stand-in when wheat is off the table.",
     "Sin gluten y suave: el sustituto del cuscús cuando el trigo queda fuera."),
    ("polenta", "Polenta", "Polenta", "Polenta",
     "carb", "base", 85, 2.0, 18.0, 0.4, 1.0, 0, 200, vegan(),
     "Le maïs en purée dorée, sans gluten, et l'un des féculents les moins denses une fois cuit.",
     "Golden corn porridge, gluten-free, and one of the least dense starches once cooked.",
     "El maíz en crema dorada, sin gluten, y uno de los farináceos menos densos ya cocido."),
    ("riz-basmati", "Riz basmati", "Basmati rice", "Arroz basmati",
     "carb", "base", 121, 3.5, 25.0, 0.4, 0.7, 0, 180, vegan(),
     "Le riz blanc à l'index glycémique le plus doux — le grain long fait une vraie différence.",
     "The white rice with the gentlest glycaemic index — the long grain genuinely matters.",
     "El arroz blanco de índice glucémico más suave: el grano largo marca una diferencia real."),
    ("vermicelles-riz", "Vermicelles de riz", "Rice noodles", "Fideos de arroz",
     "carb", "base", 109, 1.8, 25.0, 0.2, 1.0, 0, 180, vegan(),
     "Les nouilles sans gluten des soupes et des sautés : cuites en trois minutes dans l'eau du bouillon.",
     "The gluten-free noodle for soups and stir-fries: done in three minutes in the broth itself.",
     "Los fideos sin gluten de sopas y salteados: listos en tres minutos en el propio caldo."),
    ("pates-blanches", "Pâtes blanches", "White pasta", "Pasta blanca",
     "carb", "base", 155, 5.5, 30.0, 0.9, 1.8, 0, 180, vegan(gluten=True),
     "Moins de fibres que les complètes, mais al dente leur index reste modéré — le vrai écart est plus petit que sa réputation.",
     "Less fibre than wholewheat, but cooked al dente the index stays moderate — the real gap is smaller than its reputation.",
     "Menos fibra que la integral, pero al dente su índice sigue moderado: la diferencia real es menor que su fama."),
    ("gnocchis", "Gnocchis", "Gnocchi", "Ñoquis",
     "carb", "moderate", 160, 4.0, 32.0, 1.0, 1.5, 0, 180, vegan(gluten=True),
     "De la pomme de terre densifiée à la farine : le même volume rassasie moins que la pomme de terre entière.",
     "Potato densified with flour: the same volume fills less than the whole potato would.",
     "Patata densificada con harina: el mismo volumen sacia menos que la patata entera."),
    ("pain-seigle", "Pain de seigle", "Rye bread", "Pan de centeno",
     "carb", "base", 250, 8.5, 45.0, 1.5, 7.0, 0, 80, vegan(gluten=True),
     "Le pain le plus riche en fibres du rayon, et celui qui tient le plus longtemps au corps.",
     "The highest-fibre bread on the shelf, and the one that stays with you longest.",
     "El pan más rico en fibra del estante, y el que más tiempo acompaña."),
    ("pain-cereales", "Pain aux céréales", "Multigrain bread", "Pan multicereales",
     "carb", "base", 265, 10.0, 43.0, 4.5, 6.0, 0, 80, vegan(gluten=True),
     "Les graines ajoutent des fibres et un peu de gras utile — vérifie juste que « céréales » ne veut pas dire « décor ».",
     "The seeds add fibre and some useful fat — just check that “multigrain” doesn't mean “decoration”.",
     "Las semillas añaden fibra y algo de grasa útil; comprueba solo que «multicereales» no signifique «decoración»."),
    ("wrap-ble", "Wrap de blé", "Wheat wrap", "Tortilla de trigo",
     "carb", "moderate", 300, 8.0, 50.0, 7.0, 3.0, 0, 60, vegan(gluten=True),
     "Plus dense que le pain à poids égal, et le moelleux vient d'huiles ajoutées : deux wraps valent une demi-baguette.",
     "Denser than bread gram for gram, and the softness comes from added oils: two wraps equal half a baguette.",
     "Más densa que el pan a igual peso, y lo tierno viene de aceites añadidos: dos tortillas valen media barra."),
    ("muesli-nature", "Muesli sans sucre ajouté", "No-added-sugar muesli", "Muesli sin azúcar añadido",
     "carb", "base", 360, 10.0, 60.0, 7.0, 8.0, 0, 60, vegan(gluten=True),
     "Avoine, fruits secs et graines, rien d'enrobé : le granola sans la friture au sirop.",
     "Oats, dried fruit and seeds, nothing coated: granola without the syrup fry-up.",
     "Avena, fruta seca y semillas, nada recubierto: la granola sin la fritura de sirope."),
    ("granola", "Granola", "Granola", "Granola",
     "carb", "moderate", 450, 8.0, 55.0, 20.0, 6.0, 0, 50, vegan(gluten=True),
     "Du muesli cuit dans le sucre et l'huile : croustillant payé 90 kcal de plus les 100 g.",
     "Muesli baked in sugar and oil: the crunch costs 90 kcal more per 100 g.",
     "Muesli horneado en azúcar y aceite: el crujiente cuesta 90 kcal más por 100 g."),
    ("cereales-mais", "Céréales de maïs (corn flakes)", "Corn flakes", "Copos de maíz",
     "carb", "moderate", 380, 7.0, 84.0, 0.9, 3.0, 0, 40, vegan(),
     "Presque de l'amidon pur, digéré à la vitesse du sucre : le bol du matin qui a faim à dix heures.",
     "Nearly pure starch, digested at sugar speed: the breakfast bowl that is hungry again by ten.",
     "Casi almidón puro, digerido a velocidad de azúcar: el bol de la mañana que vuelve a tener hambre a las diez."),
    ("petits-pois", "Petits pois", "Green peas", "Guisantes",
     "carb", "base", 81, 5.4, 14.0, 0.4, 5.7, 0, 150, vegan(),
     "À mi-chemin entre légume et féculent, avec les protéines des deux réunies.",
     "Halfway between vegetable and starch, with the protein of both combined.",
     "A medio camino entre verdura y farináceo, con la proteína de ambos."),
    ("mais-doux", "Maïs doux", "Sweetcorn", "Maíz dulce",
     "carb", "base", 96, 3.4, 19.0, 1.5, 2.7, 0, 140, vegan(),
     "Le féculent qui se prend pour un légume : parfait en salade, tant qu'il est compté comme féculent.",
     "The starch that thinks it's a vegetable: perfect in salads, as long as it's counted as starch.",
     "El farináceo que se cree verdura: perfecto en ensalada, siempre que se cuente como farináceo."),
]
