# -*- coding: utf-8 -*-
"""Viandes, volailles, poissons, mer, œufs et laitages.

Valeurs pour 100 g prêt à consommer (viandes et poissons cuits), sources
CIQUAL / USDA arrondies. Champs :
(id, fr, en, es, role, tier, kcal, prot, gluc, lip, fibres, alcool, portion, régimes, raison fr, en, es)
"""
from common import fish, meat, pork, vegetarian

MEATS = [
    ("cuisse-de-poulet", "Cuisse de poulet (sans peau)", "Chicken thigh (skinless)", "Muslo de pollo (sin piel)",
     "protein", "base", 179, 24.0, 0, 8.7, 0, 0, 150, meat(),
     "Plus grasse que le blanc mais bien plus tendre : celle qu'on finit vraiment quand le blanc lasse.",
     "Fattier than breast but far more tender: the one you actually finish when breast gets old.",
     "Más graso que la pechuga pero mucho más tierno: el que de verdad te terminas cuando la pechuga cansa."),
    ("poulet-roti", "Poulet rôti (avec peau)", "Roast chicken (with skin)", "Pollo asado (con piel)",
     "protein", "moderate", 239, 27.0, 0, 14.0, 0, 0, 150, meat(),
     "La peau double presque les lipides du blanc. Un très bon plat — qui se pèse, lui.",
     "The skin nearly doubles the fat of plain breast. A fine meal — one you weigh.",
     "La piel casi duplica la grasa de la pechuga. Un buen plato, pero de los que se pesan."),
    ("lapin", "Lapin", "Rabbit", "Conejo",
     "protein", "base", 173, 29.0, 0, 5.5, 0, 0, 150, meat(),
     "Aussi maigre que la dinde, plus riche en vitamine B3, et injustement oublié.",
     "As lean as turkey, richer in niacin, and unfairly forgotten.",
     "Tan magro como el pavo, más rico en niacina e injustamente olvidado."),
    ("veau-escalope", "Escalope de veau", "Veal escalope", "Escalope de ternera lechal",
     "protein", "base", 172, 31.0, 0, 4.7, 0, 0, 150, meat(),
     "Le profil du blanc de poulet, avec le fer d'une viande rouge claire.",
     "The profile of chicken breast, with the iron of a light red meat.",
     "El perfil de la pechuga de pollo, con el hierro de una carne roja clara."),
    ("boeuf-15", "Bœuf haché 15 %", "Beef mince 15 %", "Carne picada de ternera 15 %",
     "protein", "moderate", 250, 24.0, 0, 17.0, 0, 0, 150, meat(),
     "Cent kilocalories de plus que le 5 % pour la même portion : le pourcentage sur la barquette est la seule chose à lire.",
     "A hundred more kilocalories than the 5 % for the same portion: the percentage on the tray is the only thing to read.",
     "Cien kilocalorías más que el 5 % por la misma ración: el porcentaje de la bandeja es lo único que hay que leer."),
    ("rosbif", "Rosbif", "Roast beef", "Rosbif",
     "protein", "base", 160, 28.0, 0, 5.0, 0, 0, 130, meat(),
     "Du bœuf maigre qui se tranche froid : la protéine des déjeuners pressés.",
     "Lean beef that slices cold: the protein of hurried lunches.",
     "Ternera magra que se corta en frío: la proteína de los almuerzos con prisa."),
    ("agneau-gigot", "Gigot d'agneau", "Leg of lamb", "Pierna de cordero",
     "protein", "moderate", 230, 26.0, 0, 14.0, 0, 0, 150, meat(),
     "Riche en zinc et en fer, mais deux fois plus gras que la volaille maigre : un plat du dimanche, pas du mardi.",
     "Rich in zinc and iron, but twice the fat of lean poultry: a Sunday dish, not a Tuesday one.",
     "Rico en zinc y hierro, pero con el doble de grasa que el ave magra: plato de domingo, no de martes."),
    ("foie-de-volaille", "Foie de volaille", "Chicken liver", "Hígado de pollo",
     "protein", "base", 167, 24.0, 1.0, 6.5, 0, 0, 100, meat(),
     "L'aliment le plus dense en fer et en vitamine A du catalogue. Une fois par semaine suffit, et c'est déjà beaucoup.",
     "The most iron- and vitamin-A-dense food in this catalogue. Once a week is enough — and already a lot.",
     "El alimento más denso en hierro y vitamina A del catálogo. Una vez por semana basta, y ya es mucho."),
    ("porc-echine", "Échine de porc", "Pork shoulder", "Aguja de cerdo",
     "protein", "moderate", 236, 25.0, 0, 15.0, 0, 0, 150, pork(),
     "Le morceau moelleux du porc — deux fois plus gras que le filet, qui reste le choix des jours comptés.",
     "The tender cut of pork — twice the fat of the loin, which stays the pick on counted days.",
     "El corte tierno del cerdo: el doble de grasa que el lomo, que sigue siendo la opción los días contados."),
    ("jambon-blanc", "Jambon blanc découenné", "Lean cooked ham", "Jamón cocido sin corteza",
     "protein", "moderate", 115, 20.0, 1.0, 3.5, 0, 0, 100, pork(),
     "La charcuterie la plus maigre du rayon — mais du sel et des nitrites : dépanner, pas fonder.",
     "The leanest of the deli counter — but salt and nitrites: a stopgap, not a staple.",
     "El fiambre más magro del mostrador, pero con sal y nitritos: saca de un apuro, no es una base."),
    ("viande-des-grisons", "Viande des Grisons", "Air-dried beef", "Cecina",
     "protein", "moderate", 175, 37.0, 0.5, 2.5, 0, 0, 60, meat(),
     "37 g de protéines aux 100 g, record du catalogue — payé au prix d'une salaison intense.",
     "37 g of protein per 100 g, the catalogue record — paid for with heavy curing salt.",
     "37 g de proteína por 100 g, récord del catálogo, pagados con una salazón intensa."),
    ("bacon", "Bacon", "Bacon", "Beicon",
     "protein", "occasional", 400, 30.0, 1.0, 30.0, 0, 0, 40, pork(),
     "Les trois quarts des calories viennent du gras et du fumage-salage. Le goût d'accord, la base non.",
     "Three quarters of the calories come from fat, smoke and salt. Fine as a flavour, not as a base.",
     "Tres cuartos de las calorías vienen de la grasa y del ahumado con sal. Como sabor vale, como base no."),
    ("saucisse-toulouse", "Saucisse de Toulouse", "Fresh pork sausage", "Salchicha fresca",
     "protein", "occasional", 300, 16.0, 1.0, 26.0, 0, 0, 125, pork(),
     "Deux fois plus de gras que de protéines : la protéine y est un passager, pas le conducteur.",
     "Twice as much fat as protein: the protein rides along, it does not drive.",
     "El doble de grasa que de proteína: la proteína va de pasajera, no conduce."),
    ("merguez", "Merguez", "Merguez sausage", "Merguez",
     "protein", "occasional", 280, 15.0, 2.0, 24.0, 0, 0, 100, meat(),
     "Le profil de la saucisse, version agneau-bœuf : un plaisir de barbecue qui compte comme tel.",
     "The sausage profile, lamb-and-beef edition: a barbecue treat that counts as one.",
     "El perfil de la salchicha en versión cordero-ternera: un capricho de barbacoa que cuenta como tal."),
]

SEA = [
    ("truite", "Truite", "Trout", "Trucha",
     "protein", "base", 148, 21.0, 0, 6.7, 0, 0, 140, fish(),
     "Les oméga-3 du saumon en version locale et souvent moins chère.",
     "Salmon's omega-3s in a local, often cheaper package.",
     "Los omega-3 del salmón en versión local y a menudo más barata."),
    ("maquereau", "Maquereau", "Mackerel", "Caballa",
     "protein", "base", 205, 19.0, 0, 14.0, 0, 0, 140, fish(),
     "Parmi les plus riches en oméga-3 du rayon, pour trois fois moins cher que le saumon.",
     "Among the richest in omega-3 at the counter, for a third of the price of salmon.",
     "De los más ricos en omega-3 del mostrador, por un tercio del precio del salmón."),
    ("hareng", "Hareng", "Herring", "Arenque",
     "protein", "base", 190, 18.0, 0, 13.0, 0, 0, 130, fish(),
     "Oméga-3, vitamine D et sélénium — le petit poisson gras que la mer du Nord mange depuis toujours.",
     "Omega-3, vitamin D and selenium — the oily little fish the North Sea has always lived on.",
     "Omega-3, vitamina D y selenio: el pescadito azul del que el mar del Norte vive desde siempre."),
    ("dorade", "Dorade", "Sea bream", "Dorada",
     "protein", "base", 128, 22.0, 0, 4.4, 0, 0, 150, fish(),
     "Un poisson blanc ferme qui pardonne la cuisson — celui par lequel commencer si le poisson t'ennuie.",
     "A firm white fish that forgives the cook — the one to start with if fish bores you.",
     "Un pescado blanco firme que perdona la cocción: por el que empezar si el pescado te aburre."),
    ("bar", "Bar (loup)", "Sea bass", "Lubina",
     "protein", "base", 124, 21.0, 0, 4.0, 0, 0, 150, fish(),
     "Le maigre des poissons nobles : la texture du restaurant, les macros du cabillaud.",
     "The lean end of the fine-fish counter: restaurant texture, cod macros.",
     "Lo magro entre los pescados nobles: textura de restaurante, macros de bacalao."),
    ("colin-lieu", "Colin / lieu noir", "Pollock", "Abadejo",
     "protein", "base", 92, 20.0, 0, 1.0, 0, 0, 150, fish(),
     "Le poisson blanc le moins cher au kilo de protéines — celui des étudiants qui font leurs macros.",
     "The cheapest white fish per kilo of protein — the one for students who track macros.",
     "El pescado blanco más barato por kilo de proteína: el de los estudiantes que cuentan macros."),
    ("sole", "Sole", "Sole", "Lenguado",
     "protein", "base", 86, 18.0, 0, 1.5, 0, 0, 140, fish(),
     "Presque aussi maigre que le blanc d'œuf, et une chair qui se défait à la fourchette.",
     "Nearly as lean as egg white, with flesh that parts at the fork.",
     "Casi tan magro como la clara de huevo, con una carne que se deshace con el tenedor."),
    ("tilapia", "Tilapia", "Tilapia", "Tilapia",
     "protein", "base", 96, 20.0, 0, 1.7, 0, 0, 150, fish(),
     "Neutre en goût et imbattable en prix : la toile blanche des sauces qui ont du caractère.",
     "Neutral in taste and unbeatable on price: the blank canvas for sauces with character.",
     "Neutro de sabor e imbatible de precio: el lienzo en blanco para salsas con carácter."),
    ("thon-frais", "Thon frais", "Fresh tuna", "Atún fresco",
     "protein", "base", 144, 23.0, 0, 4.9, 0, 0, 140, fish(),
     "Le steak de la mer : la densité protéique du bœuf maigre, les oméga-3 en plus.",
     "The steak of the sea: lean beef's protein density, with omega-3 on top.",
     "El filete del mar: la densidad proteica de la ternera magra, con omega-3 de regalo."),
    ("saumon-fume", "Saumon fumé", "Smoked salmon", "Salmón ahumado",
     "protein", "moderate", 180, 23.0, 0, 10.0, 0, 0, 75, fish(),
     "Le saumon, en plus salé et bien plus cher : un plaisir d'occasion plus qu'une base d'assiette.",
     "Salmon, saltier and much dearer: an occasion food more than a plate's foundation.",
     "El salmón, más salado y bastante más caro: más un placer de ocasión que una base del plato."),
    ("anchois", "Anchois (à l'huile, égouttés)", "Anchovies (in oil, drained)", "Anchoas (en aceite, escurridas)",
     "protein", "moderate", 210, 29.0, 0, 10.0, 0, 0, 30, fish(),
     "Trente grammes suffisent à assaisonner un plat entier en protéines et en iode — et en sel, d'où la modération.",
     "Thirty grams season a whole dish with protein and iodine — and salt, hence the moderation.",
     "Treinta gramos aliñan un plato entero con proteína y yodo, y con sal: de ahí la moderación."),
    ("moules", "Moules", "Mussels", "Mejillones",
     "protein", "base", 111, 17.0, 4.0, 2.2, 0, 0, 150, fish(),
     "Fer, B12 et zinc au niveau de la viande rouge, pour moitié moins de calories.",
     "Iron, B12 and zinc at red-meat levels, for half the calories.",
     "Hierro, B12 y zinc a nivel de carne roja, con la mitad de calorías."),
    ("calamars", "Calamars", "Squid", "Calamares",
     "protein", "base", 92, 16.0, 3.0, 1.4, 0, 0, 140, fish(),
     "Maigre et élastique sous la dent — tout se joue à la cuisson : une minute, ou une heure, jamais entre les deux.",
     "Lean and springy — the cooking decides everything: one minute or one hour, never in between.",
     "Magro y firme al diente: todo se decide en la cocción, un minuto o una hora, nunca entre medias."),
    ("noix-st-jacques", "Noix de Saint-Jacques", "Scallops", "Vieiras",
     "protein", "base", 88, 17.0, 2.4, 0.8, 0, 0, 120, fish(),
     "La protéine la plus maigre de la mer après la sole — et celle qui se gâche le plus vite en cuisant trop.",
     "The leanest protein in the sea after sole — and the quickest ruined by overcooking.",
     "La proteína más magra del mar tras el lenguado, y la que antes se estropea si se pasa de cocción."),
    ("crabe", "Crabe", "Crab", "Cangrejo",
     "protein", "base", 97, 19.0, 0, 1.5, 0, 0, 120, fish(),
     "Le profil des crevettes avec plus de zinc — la boîte au naturel fait très bien l'affaire.",
     "The shrimp profile with more zinc — plain tinned works perfectly well.",
     "El perfil de las gambas con más zinc: la lata al natural sirve perfectamente."),
    ("surimi", "Surimi", "Surimi sticks", "Surimi",
     "protein", "moderate", 95, 8.0, 12.0, 1.5, 0, 0, 100, fish(gluten=True),
     "Moitié poisson, moitié amidon et sucre : la protéine y est plus diluée que le nom le laisse croire.",
     "Half fish, half starch and sugar: the protein is more diluted than the name suggests.",
     "Mitad pescado, mitad almidón y azúcar: la proteína está más diluida de lo que sugiere el nombre."),
]

DAIRY_EGGS = [
    ("yaourt-grec", "Yaourt grec nature", "Plain Greek yoghurt", "Yogur griego natural",
     "dairy", "moderate", 121, 6.4, 4.0, 9.0, 0, 0, 150, vegetarian(),
     "Deux fois plus gras que le skyr pour moitié moins de protéines : la douceur se paie, le skyr reste l'outil.",
     "Twice the fat of skyr for half the protein: the creaminess has a price — skyr stays the tool.",
     "El doble de grasa que el skyr con la mitad de proteína: la cremosidad se paga, el skyr sigue siendo la herramienta."),
    ("yaourt-nature", "Yaourt nature", "Plain yoghurt", "Yogur natural",
     "dairy", "base", 61, 4.0, 5.0, 3.0, 0, 0, 125, vegetarian(),
     "Le dessert par défaut qui ne coûte presque rien au total de la journée.",
     "The default dessert that costs the day's total almost nothing.",
     "El postre por defecto que apenas cuesta nada al total del día."),
    ("petit-suisse", "Petit-suisse (3 %)", "Petit-suisse fresh cheese", "Petit-suisse",
     "dairy", "base", 87, 9.3, 3.5, 3.6, 0, 0, 120, vegetarian(),
     "Le fromage blanc en format qui se finit : la protéine d'un dessert, la taille d'un goûter.",
     "Fromage blanc in a format you finish: a dessert's protein, a snack's size.",
     "El queso fresco en formato que se termina: la proteína de un postre, el tamaño de una merienda."),
    ("kefir-lait", "Kéfir de lait", "Milk kefir", "Kéfir de leche",
     "drink", "base", 55, 3.4, 4.5, 2.5, 0, 0, 250, vegetarian(),
     "Un lait fermenté vivant : les macros du lait demi-écrémé, les ferments en plus.",
     "A living fermented milk: semi-skimmed macros with live cultures on top.",
     "Una leche fermentada viva: las macros de la semidesnatada con fermentos de regalo."),
    ("mozzarella", "Mozzarella", "Mozzarella", "Mozzarella",
     "dairy", "moderate", 280, 18.0, 2.0, 22.0, 0, 0, 60, vegetarian(),
     "Plus légère que la plupart des fromages affinés, mais une boule entière vaut un repas en calories.",
     "Lighter than most aged cheeses, but a whole ball is a meal's worth of calories.",
     "Más ligera que la mayoría de quesos curados, pero una bola entera vale un almuerzo en calorías."),
    ("ricotta", "Ricotta", "Ricotta", "Ricotta",
     "dairy", "base", 150, 9.0, 4.0, 11.0, 0, 0, 100, vegetarian(),
     "Le plus léger des fromages crémeux : là où le mascarpone triple la note, la ricotta la garde tenable.",
     "The lightest of the creamy cheeses: where mascarpone triples the bill, ricotta keeps it payable.",
     "El más ligero de los quesos cremosos: donde el mascarpone triplica la cuenta, la ricotta la deja pagable."),
    ("parmesan", "Parmesan", "Parmesan", "Parmesano",
     "dairy", "moderate", 392, 33.0, 3.2, 28.0, 0, 0, 20, vegetarian(),
     "Le plus protéiné des fromages, et tellement dense en goût que vingt grammes suffisent — c'est toute sa ruse.",
     "The most protein-rich of cheeses, and so intense that twenty grams is plenty — that is its whole trick.",
     "El queso más proteico, y tan intenso que con veinte gramos basta: ese es todo su truco."),
    ("emmental", "Emmental", "Emmental", "Emmental",
     "dairy", "moderate", 380, 28.0, 0.5, 29.0, 0, 0, 30, vegetarian(),
     "Le fromage du quotidien : correct en protéines, dense en calories — le râpé disparaît plus vite qu'on ne le compte.",
     "The everyday cheese: decent protein, dense calories — grated, it vanishes faster than you count it.",
     "El queso de diario: correcto en proteína, denso en calorías; rallado desaparece más rápido de lo que se cuenta."),
    ("chevre-buche", "Chèvre (bûche)", "Goat's cheese log", "Rulo de cabra",
     "dairy", "moderate", 290, 20.0, 2.5, 22.0, 0, 0, 40, vegetarian(),
     "Souvent mieux toléré que la vache, tout aussi calorique : le régime change, la densité non.",
     "Often better tolerated than cow's milk, just as caloric: the tolerance changes, the density doesn't.",
     "A menudo mejor tolerado que la vaca e igual de calórico: cambia la tolerancia, no la densidad."),
    ("caseine", "Caséine (poudre)", "Casein powder", "Caseína en polvo",
     "protein", "moderate", 370, 78.0, 8.0, 1.5, 0, 0, 30, vegetarian(),
     "La whey lente : trois heures de diffusion, la dose du soir quand le dîner a manqué de protéines.",
     "Slow whey: three hours of release, the evening scoop when dinner ran short of protein.",
     "La whey lenta: tres horas de liberación, el cazo nocturno cuando la cena se quedó corta de proteína."),
]
