# -*- coding: utf-8 -*-
"""Graisses, oléagineux, boissons, condiments et plaisirs."""
from common import alcohol, vegan, vegetarian

FATS = [
    ("noisettes", "Noisettes", "Hazelnuts", "Avellanas",
     "fat", "moderate", 628, 15.0, 17.0, 61.0, 9.7, 0, 30, vegan(),
     "La vitamine E des amandes avec plus de gras mono-insaturés — même règle : la poignée se compte.",
     "Almond's vitamin E with more monounsaturated fat — same rule: the handful gets counted.",
     "La vitamina E de las almendras con más grasa monoinsaturada; misma regla: el puñado se cuenta."),
    ("cajou", "Noix de cajou", "Cashews", "Anacardos",
     "fat", "moderate", 553, 18.0, 30.0, 44.0, 3.3, 0, 30, vegan(),
     "Les moins grasses des noix et les plus riches en glucides — d'où leur douceur, et leur facilité à disparaître.",
     "The least fatty of the nuts and the richest in carbs — hence their sweetness, and how fast they vanish.",
     "Los menos grasos de los frutos secos y los más ricos en carbohidratos: de ahí su dulzor, y lo rápido que desaparecen."),
    ("pistaches", "Pistaches", "Pistachios", "Pistachos",
     "fat", "moderate", 560, 20.0, 28.0, 45.0, 10.6, 0, 30, vegan(),
     "Les plus protéinées du bocal, et la coque impose un rythme qui laisse la satiété parler.",
     "The most protein-rich in the jar, and the shell sets a pace that lets fullness speak.",
     "Los más proteicos del bote, y la cáscara impone un ritmo que deja hablar a la saciedad."),
    ("cacahuetes", "Cacahuètes non salées", "Unsalted peanuts", "Cacahuetes sin sal",
     "fat", "moderate", 567, 26.0, 16.0, 49.0, 8.5, 0, 30, vegan(),
     "Autant de protéines que bien des viandes au gramme — mais neuf fois plus de calories que le blanc de poulet.",
     "As much protein per gram as many meats — but nine times the calories of chicken breast.",
     "Tanta proteína por gramo como muchas carnes, pero nueve veces las calorías de la pechuga."),
    ("noix-bresil", "Noix du Brésil", "Brazil nuts", "Nueces de Brasil",
     "fat", "moderate", 659, 14.0, 12.0, 67.0, 7.5, 0, 20, vegan(),
     "Deux noix couvrent le sélénium du jour — au-delà de quatre par jour, il finit par être en excès.",
     "Two nuts cover the day's selenium — past four a day it eventually tips into excess.",
     "Dos nueces cubren el selenio del día; más de cuatro diarias acaban siendo un exceso."),
    ("noix-pecan", "Noix de pécan", "Pecans", "Nueces pecanas",
     "fat", "moderate", 691, 9.0, 14.0, 72.0, 9.6, 0, 25, vegan(),
     "La plus grasse des noix courantes : le beurre du rayon oléagineux, à peser comme le beurre.",
     "The fattiest of the common nuts: the butter of the nut aisle, weighed like butter.",
     "El más graso de los frutos secos comunes: la mantequilla del estante, a pesar como la mantequilla."),
    ("puree-amande", "Purée d'amande", "Almond butter", "Crema de almendras",
     "fat", "moderate", 614, 21.0, 19.0, 53.0, 10.0, 0, 20, vegan(),
     "L'amande en version tartinable : les mêmes qualités, sans le frein de la mastication — la cuillère se pèse.",
     "Almonds in spreadable form: the same virtues without the chewing brake — the spoon gets weighed.",
     "La almendra untable: las mismas virtudes sin el freno de masticar; la cucharada se pesa."),
    ("tahini", "Tahini (purée de sésame)", "Tahini", "Tahini",
     "fat", "moderate", 595, 17.0, 21.0, 54.0, 9.3, 0, 20, vegan(),
     "Le calcium le plus dense du rayon végétal, et la base d'une sauce qui fait manger n'importe quel légume.",
     "The densest plant calcium on the shelf, and the base of a sauce that sells any vegetable.",
     "El calcio vegetal más denso del estante, y la base de una salsa que hace comer cualquier verdura."),
    ("graines-tournesol", "Graines de tournesol", "Sunflower seeds", "Pipas de girasol",
     "fat", "moderate", 584, 21.0, 20.0, 51.0, 8.6, 0, 25, vegan(),
     "La vitamine E la moins chère du magasin, sur le yaourt ou la salade plutôt qu'à la volée.",
     "The cheapest vitamin E in the shop — on yoghurt or salad, not by the fistful.",
     "La vitamina E más barata de la tienda, sobre el yogur o la ensalada y no a puñados."),
    ("graines-sesame", "Graines de sésame", "Sesame seeds", "Semillas de sésamo",
     "fat", "moderate", 573, 18.0, 23.0, 50.0, 11.8, 0, 15, vegan(),
     "Une cuillère dorée à la poêle transforme un plat entier — calcium et croquant pour quinze grammes comptés.",
     "A pan-toasted spoonful transforms a whole dish — calcium and crunch for fifteen counted grams.",
     "Una cucharada dorada en la sartén transforma el plato: calcio y crujido por quince gramos contados."),
    ("olives", "Olives", "Olives", "Aceitunas",
     "fat", "base", 145, 1.0, 3.8, 15.0, 3.3, 0, 30, vegan(),
     "L'huile d'olive encore dans son fruit, fibres comprises — l'apéritif le plus défendable du placard.",
     "Olive oil still inside its fruit, fibre included — the most defensible apéritif in the cupboard.",
     "El aceite de oliva aún en su fruto, fibra incluida: el aperitivo más defendible de la despensa."),
    ("huile-noix", "Huile de noix", "Walnut oil", "Aceite de nuez",
     "fat", "base", 900, 0, 0, 100.0, 0, 0, 10, vegan(),
     "L'oméga-3 végétal en assaisonnement — jamais à la poêle, la chaleur détruit précisément ce qu'on lui achète.",
     "Plant omega-3 as a dressing — never in the pan: heat destroys exactly what you bought it for.",
     "El omega-3 vegetal para aliñar; nunca a la sartén: el calor destruye justo lo que le compras."),
    ("huile-coco", "Huile de coco", "Coconut oil", "Aceite de coco",
     "fat", "occasional", 900, 0, 0, 100.0, 0, 0, 10, vegan(),
     "Plus saturée que le beurre malgré sa réputation — la mode a couru plus vite que les données.",
     "More saturated than butter despite its reputation — the trend outran the data.",
     "Más saturado que la mantequilla pese a su fama: la moda corrió más que los datos."),
    ("creme-fraiche", "Crème fraîche (30 %)", "Crème fraîche (30 %)", "Nata fresca (30 %)",
     "fat", "moderate", 292, 2.4, 3.0, 30.0, 0, 0, 30, vegetarian(),
     "Une cuillère à soupe vaut une noix de beurre : le moelleux des sauces, au gramme près.",
     "One tablespoon equals a knob of butter: sauce silkiness, by the counted gram.",
     "Una cucharada vale un trozo de mantequilla: la cremosidad de las salsas, gramo a gramo."),
    ("creme-legere", "Crème légère (15 %)", "Light cream (15 %)", "Nata ligera (15 %)",
     "fat", "base", 162, 2.6, 4.0, 15.0, 0, 0, 30, vegetarian(),
     "La moitié des calories de l'entière pour le même geste en cuisine — l'allègement qui ne se goûte pas.",
     "Half the calories of full cream for the same kitchen move — the lightening you cannot taste.",
     "La mitad de calorías que la entera para el mismo gesto en cocina: el aligerado que no se nota."),
    ("coco-rape", "Noix de coco râpée", "Desiccated coconut", "Coco rallado",
     "fat", "moderate", 660, 6.9, 24.0, 65.0, 16.3, 0, 15, vegan(),
     "Des fibres records, mais du gras saturé aux deux tiers : la pincée qui parfume, pas la poignée.",
     "Record fibre, but two-thirds saturated fat: the pinch that flavours, not the handful.",
     "Fibra récord, pero dos tercios de grasa saturada: la pizca que aromatiza, no el puñado."),
]

DRINKS = [
    ("boisson-amande", "Boisson à l'amande (sans sucres)", "Unsweetened almond drink", "Bebida de almendra (sin azúcar)",
     "drink", "base", 15, 0.5, 0.2, 1.2, 0.3, 0, 250, vegan(),
     "Presque de l'eau blanchie : très légère, mais sans les protéines du lait ni de la boisson soja.",
     "Nearly whitened water: very light, but without the protein of milk or soy drink.",
     "Casi agua blanqueada: ligerísima, pero sin la proteína de la leche ni de la bebida de soja."),
    ("boisson-avoine", "Boisson à l'avoine", "Oat drink", "Bebida de avena",
     "drink", "moderate", 46, 0.8, 7.0, 1.5, 0.8, 0, 250, vegan(gluten=True),
     "La plus douce des boissons végétales — parce que son amidon est déjà à moitié sucre.",
     "The sweetest of the plant drinks — because its starch is already half sugar.",
     "La más dulce de las bebidas vegetales, porque su almidón ya es medio azúcar."),
    ("kombucha", "Kombucha", "Kombucha", "Kombucha",
     "drink", "moderate", 20, 0, 4.8, 0, 0, 0, 250, vegan(),
     "Un thé fermenté vivant, bien moins sucré qu'un soda — mais pas gratuit pour autant : l'étiquette varie du simple au triple.",
     "A living fermented tea, far less sweet than soda — but not free either: labels vary threefold.",
     "Un té fermentado vivo, mucho menos dulce que un refresco, pero no gratis: la etiqueta varía del simple al triple."),
    ("eau-gazeuse", "Eau gazeuse", "Sparkling water", "Agua con gas",
     "drink", "base", 0, 0, 0, 0, 0, 0, 330, vegan(),
     "Le soda sans le soda : les bulles occupent la place que le sucre réclamait.",
     "Soda without the soda: the bubbles fill the space the sugar was claiming.",
     "El refresco sin el refresco: las burbujas ocupan el sitio que pedía el azúcar."),
    ("soda-light", "Soda light", "Diet soda", "Refresco light",
     "drink", "moderate", 1, 0, 0.1, 0, 0, 0, 330, vegan(),
     "Zéro calorie, vrai ; mais il entretient l'appel du très sucré — l'outil de transition, pas la destination.",
     "Zero calories, true; but it keeps the taste for intense sweetness alive — a transition tool, not the destination.",
     "Cero calorías, cierto; pero mantiene vivo el gusto por lo muy dulce: herramienta de transición, no destino."),
    ("the-noir", "Thé noir", "Black tea", "Té negro",
     "drink", "base", 1, 0, 0.2, 0, 0, 0, 250, vegan(),
     "La caféine du café en version douce et étalée — sans sucre, il ne compte simplement pas.",
     "Coffee's caffeine, gentler and slower — unsweetened, it simply doesn't count.",
     "La cafeína del café en versión suave y prolongada; sin azúcar, simplemente no cuenta."),
    ("chocolat-chaud", "Chocolat chaud", "Hot chocolate", "Chocolate caliente",
     "drink", "occasional", 77, 3.2, 10.5, 2.5, 0.8, 0, 250, vegetarian(),
     "Un dessert qui se boit : la tasse du soir vaut deux carrés de chocolat noir — sans le croquant qui arrête.",
     "A drinkable dessert: the evening mug equals two squares of dark chocolate — without the snap that stops you.",
     "Un postre que se bebe: la taza de la noche vale dos onzas de chocolate negro, sin el crujido que frena."),
    ("vin-rouge", "Vin rouge", "Red wine", "Vino tinto",
     "drink", "occasional", 85, 0.1, 2.6, 0, 0, 10.6, 125, alcohol(),
     "Le verre de 125 ml porte 85 kcal, presque toutes d'alcool — le polyphénol du raisin n'a jamais compensé l'éthanol.",
     "The 125 ml glass carries 85 kcal, nearly all of it alcohol — the grape's polyphenols never offset the ethanol.",
     "La copa de 125 ml lleva 85 kcal, casi todas de alcohol: los polifenoles de la uva nunca compensaron el etanol."),
    ("spiritueux", "Spiritueux (40°)", "Spirits (40 %)", "Licores (40°)",
     "drink", "occasional", 231, 0, 0.2, 0, 0, 33.0, 40, alcohol(),
     "Le shot de 4 cl vaut 92 kcal d'alcool pur — et c'est le mélange soda qui double l'addition.",
     "A 4 cl shot is 92 kcal of pure alcohol — and it's the soda mixer that doubles the bill.",
     "El chupito de 4 cl son 92 kcal de alcohol puro, y es el refresco de la mezcla el que dobla la cuenta."),
]

EXTRAS = [
    ("miel", "Miel", "Honey", "Miel",
     "treat", "moderate", 304, 0.3, 82.0, 0, 0.2, 0, 15, vegetarian(),
     "Du sucre avec une histoire : quelques traces d'antioxydants, mais la cuillère se compte comme du sucre.",
     "Sugar with a backstory: trace antioxidants, but the spoonful counts as sugar.",
     "Azúcar con historia: trazas de antioxidantes, pero la cucharada cuenta como azúcar."),
    ("confiture", "Confiture", "Jam", "Mermelada",
     "treat", "moderate", 240, 0.4, 58.0, 0.1, 1.0, 0, 20, vegan(),
     "Un tiers de fruit, deux tiers de sucre : la fine couche sur le pain, pas la cuillère dans le pot.",
     "One third fruit, two thirds sugar: the thin layer on bread, not the spoon in the jar.",
     "Un tercio de fruta, dos tercios de azúcar: la capa fina en el pan, no la cuchara en el bote."),
    ("sirop-erable", "Sirop d'érable", "Maple syrup", "Sirope de arce",
     "treat", "moderate", 260, 0, 67.0, 0, 0, 0, 20, vegan(),
     "Un sucre un peu moins dense que le miel, au goût qui porte plus loin : on en met moins, c'est tout son intérêt.",
     "A sugar slightly less dense than honey with a flavour that carries further: you use less — that is its whole point.",
     "Un azúcar algo menos denso que la miel con un sabor que llega más lejos: se usa menos, y ese es todo su interés."),
    ("pate-a-tartiner", "Pâte à tartiner", "Chocolate hazelnut spread", "Crema de cacao y avellanas",
     "treat", "occasional", 539, 6.0, 57.0, 31.0, 3.4, 0, 20, vegetarian(),
     "Plus de la moitié sucre, un tiers huile de palme : la noisette de l'étiquette est surtout sur l'étiquette.",
     "More than half sugar, a third palm oil: the hazelnut on the label lives mostly on the label.",
     "Más de la mitad azúcar y un tercio aceite de palma: la avellana de la etiqueta vive sobre todo en la etiqueta."),
    ("bonbons", "Bonbons", "Sweets", "Gominolas",
     "treat", "occasional", 350, 0.1, 87.0, 0.1, 0, 0, 30, vegan(),
     "Du sucre à l'état pur, sans même le gras qui rassasie un peu : le paquet se finit parce que rien n'arrête.",
     "Pure sugar without even the fat that slightly fills: the bag empties because nothing pushes back.",
     "Azúcar en estado puro, sin siquiera la grasa que algo sacia: la bolsa se acaba porque nada frena."),
    ("barre-chocolatee", "Barre chocolatée", "Chocolate bar", "Barrita de chocolate",
     "treat", "occasional", 480, 5.0, 60.0, 24.0, 1.5, 0, 45, vegetarian(),
     "Le distributeur de dix-sept heures : 250 kcal en quatre-vingt-dix secondes, refaim une heure après.",
     "The 5 p.m. vending machine: 250 kcal in ninety seconds, hungry again an hour later.",
     "La máquina de las cinco: 250 kcal en noventa segundos, y hambre otra vez una hora después."),
    ("gateau-chocolat", "Gâteau au chocolat", "Chocolate cake", "Tarta de chocolate",
     "treat", "occasional", 410, 5.0, 50.0, 21.0, 2.0, 0, 80, vegetarian(),
     "La part d'anniversaire vaut un déjeuner en calories — elle se mange à l'anniversaire, pas au bureau le mardi.",
     "The birthday slice is a lunch's worth of calories — eaten at the birthday, not at the desk on a Tuesday.",
     "La porción de cumpleaños vale un almuerzo en calorías: se come en el cumpleaños, no en la oficina un martes."),
    ("sorbet", "Sorbet", "Sorbet", "Sorbete",
     "treat", "moderate", 130, 0.5, 32.0, 0.1, 0.5, 0, 80, vegan(),
     "La glace sans la crème : moitié moins de calories que la crème glacée, et le fruit en premier ingrédient.",
     "Ice cream without the cream: half the calories of dairy ice cream, with fruit as the first ingredient.",
     "El helado sin la nata: la mitad de calorías que el helado cremoso, con la fruta como primer ingrediente."),
    ("frites", "Frites", "French fries", "Patatas fritas (de guarnición)",
     "treat", "occasional", 310, 3.4, 40.0, 15.0, 3.8, 0, 150, vegan(),
     "La pomme de terre a triplé ses calories dans le bain d'huile — au four, les « frites » maison en gardent la moitié.",
     "The potato tripled its calories in the oil bath — oven-baked, home “fries” keep half as many.",
     "La patata triplicó sus calorías en el baño de aceite; al horno, las «fritas» caseras se quedan en la mitad."),
    ("burger", "Burger de fast-food", "Fast-food burger", "Hamburguesa de comida rápida",
     "treat", "occasional", 280, 13.0, 28.0, 13.0, 1.5, 0, 220, ["omnivore"],
     "Le double-fromage dépasse les 600 kcal avant les frites — le burger maison au bœuf 5 % en vaut la moitié.",
     "The double-cheese passes 600 kcal before the fries — a home burger on 5 % beef is worth half that.",
     "La doble con queso pasa de 600 kcal antes de las patatas; la casera con carne al 5 % vale la mitad."),
    ("nuggets", "Nuggets de poulet", "Chicken nuggets", "Nuggets de pollo",
     "treat", "occasional", 296, 15.0, 18.0, 18.0, 1.0, 0, 100, ["omnivore"],
     "Moitié poulet, moitié panure frite : la protéine annoncée arrive noyée dans l'huile du bain.",
     "Half chicken, half fried coating: the advertised protein arrives drowned in fryer oil.",
     "Mitad pollo, mitad rebozado frito: la proteína anunciada llega ahogada en el aceite de freír."),
    ("mayonnaise", "Mayonnaise", "Mayonnaise", "Mayonesa",
     "fat", "occasional", 680, 1.0, 2.5, 74.0, 0, 0, 15, vegetarian(),
     "De l'huile fouettée : la cuillère à soupe vaut 100 kcal, et personne ne s'arrête à une cuillère.",
     "Whipped oil: the tablespoon is 100 kcal, and nobody stops at one tablespoon.",
     "Aceite batido: la cucharada vale 100 kcal, y nadie se queda en una cucharada."),
    ("ketchup", "Ketchup", "Ketchup", "Kétchup",
     "treat", "moderate", 100, 1.2, 23.0, 0.2, 0.3, 0, 15, vegan(),
     "Un quart de sucre — quatre fois moins grave que la mayonnaise, quatre fois plus que la tomate qu'il invoque.",
     "A quarter sugar — four times better than mayo, four times worse than the tomato it claims.",
     "Una cuarta parte de azúcar: cuatro veces mejor que la mayonesa, cuatro veces peor que el tomate que invoca."),
    ("moutarde", "Moutarde", "Mustard", "Mostaza",
     "treat", "base", 66, 4.4, 5.8, 3.3, 1.5, 0, 10, vegan(),
     "Le condiment qui a du goût sans avoir de calories qui comptent : la base des sauces qui ne coûtent rien.",
     "The condiment with taste but no calories worth counting: the base of sauces that cost nothing.",
     "El condimento con sabor y sin calorías que cuenten: la base de las salsas que no cuestan nada."),
    ("cornichons", "Cornichons", "Gherkins", "Pepinillos",
     "vegetable", "base", 14, 0.6, 2.2, 0.2, 1.0, 0, 40, vegan(),
     "Le croquant acide qui coupe l'envie de finir le plat — pour presque rien, sel mis à part.",
     "The sour crunch that kills the urge to finish the dish — for nearly nothing, salt aside.",
     "El crujido ácido que corta las ganas de rebañar, por casi nada, sal aparte."),
    ("sauce-tomate", "Sauce tomate nature", "Plain tomato sauce", "Tomate frito casero",
     "vegetable", "base", 38, 1.4, 6.0, 1.0, 1.8, 0, 100, vegan(),
     "La tomate concentrée par la cuisson, lycopène compris : la sauce qui compte comme un légume.",
     "Tomato concentrated by cooking, lycopene included: the sauce that counts as a vegetable.",
     "El tomate concentrado por la cocción, licopeno incluido: la salsa que cuenta como verdura."),
    ("pesto", "Pesto", "Pesto", "Pesto",
     "fat", "moderate", 460, 5.0, 6.0, 46.0, 1.5, 0, 25, vegetarian(),
     "Basilic, oui — porté par l'huile et le fromage : deux cuillères assaisonnent, quatre doublent le plat.",
     "Basil, yes — carried by oil and cheese: two spoonfuls season, four double the dish.",
     "Albahaca, sí, a hombros de aceite y queso: dos cucharadas aliñan, cuatro doblan el plato."),
    ("sauce-soja", "Sauce soja", "Soy sauce", "Salsa de soja",
     "treat", "base", 53, 8.0, 5.0, 0, 0.8, 0, 15, vegan(gluten=True),
     "Du goût presque sans calories — c'est du sel liquide : la version réduite en sodium change vraiment la donne.",
     "Taste with almost no calories — it is liquid salt: the reduced-sodium version genuinely matters.",
     "Sabor casi sin calorías, pero es sal líquida: la versión baja en sodio cambia de verdad las cosas."),
]
